### ISSUE TITLE
maxdim=0

### ISSUE THREAD

**Issue by mglisse** [giotto-ai/giotto-ph#39]
Hello,
I tried to run `gph.ripser_parallel(np.array([[1.,2],[3,4],[5,0]]), maxdim=0)` but it segfaults (while it works with maxdim=1).

**Comment by MonkeyBreaker** [comment]
Hello,

Thank you for reporting the issue. After debugging what was going on, I found out a fix.
Currently a PR (#40) is in progress for patching this issue.

Sorry that you encountered a bug and thank you for reporting it with an example.

Best,
Julián

**Comment by MonkeyBreaker** [comment]
The fix is now merged but currently not available in Pypi.
We will soon release version 0.2.0, but on the meantime if you want to work with `giotto-ph` with `maxdim=0` fix, you can follow the [developer installation](https://giotto-ai.github.io/giotto-ph/build/html/installation.html#developer-installation).
