### ISSUE TITLE
Extend dense backend to cover case of non-zero diagonal weights

### ISSUE THREAD

**Issue by ulupo** [giotto-ai/giotto-ph#56]
Using weighted Rips filtrations means a dense `dm` is computed but crucially it will typically have non-zero values along the diagonal.  Yet, we will use the sparse C++ backend in this case.

This causes a substantial loss in performance compared to what could be achieved with a dense backend, yet I think it is conceptually easy to cover such cases with the dense backend.  We just need to allow for the possibility to pass diagonal information as an additional piece of data, and use it in the 0-dimensional computation. The higher-dimensional computation should remain the same.

This could be a worthwhile target for v0.4.0 or later.

**Comment by MonkeyBreaker** [comment]
Good idea !

I think that this will mostly impact `compressed_distance_matrix` class.

In the [initialization](https://github.com/giotto-ai/giotto-ph/blob/2b3d6763af097762ca702222744ce097bb3588d7/gph/src/ripser.h#L301), we will need to include the diagonal which is currently skipped because it is assumed to be 0.

Also for the [operator](https://github.com/giotto-ai/giotto-ph/blob/2b3d6763af097762ca702222744ce097bb3588d7/gph/src/ripser.h#L298), this will remove a branch `i==j`.

This change will be interesting in terms of performance. 
I think that we will consume more memory in `compressed_distance_matrix`, but we will also remove a branch in `operator` and this function is called a lot.
We could maybe observe some surprise !

I think that the estimation for v0.4.0 is a good !
